### ISSUE TITLE
getSocketById ?

### ISSUE THREAD

**Issue by mkgn** [SocketCluster/client-drivers#1]
Currently, I maintain an array of client sockets on the server side. Reason is based on certain events, i will have to lookup the correct client socket and emit events. I am sure socketcluster itself maintain a list of sockets internally and I should be able to get the socket by passing the id (something like getSocketById). However the Docs doesn't mention anything related to it ?

**Comment by MegaGM** [comment]
You don't have to track individual clients, SocketCluster will do that for you across all servers and all workers on them.
If you're still interested, these issues could provide you with some guidance.
https://github.com/SocketCluster/socketcluster/issues/425
https://github.com/SocketCluster/socketcluster-client/issues/39
